;;; cljstyle-format-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cljstyle-format.el

 (autoload 'cljstyle-format-buffer "cljstyle-format" nil t)
 (autoload 'cljstyle-format-region "cljstyle-format" nil t)
 (autoload 'cljstyle-format-on-save-mode "cljstyle-format" nil t)
(register-definition-prefixes "cljstyle-format" '("cljstyle-format-"))

;;; End of scraped data

(provide 'cljstyle-format-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cljstyle-format-autoloads.el ends here
